import type { ScenarioDefinition } from "./types";

/** Regression fixtures — expected strategy IDs locked by snapshot tests */
export const QA_SCENARIOS: ScenarioDefinition[] = [
  {
    id: "dead_inventory",
    label: "Dead Inventory",
    description: "High inventory, near-zero sales",
    expectedStrategyId: "pause_ads",
    merchantMode: "inventory_clearance",
    product: {
      productId: "qa-dead-1",
      title: "Stale Moisturizer",
      price: 48,
      unitCost: 14,
      unitsSold30d: 2,
      inventory: 95,
      inventoryAgeDays: 120,
      costSource: "shopify",
    },
  },
  {
    id: "roas_collapse",
    label: "ROAS Collapse",
    description: "High ad spend with poor sell-through",
    expectedStrategyId: "do_nothing",
    merchantMode: "profit",
    product: {
      productId: "qa-roas-1",
      title: "Ad-Heavy Serum",
      price: 55,
      unitCost: 18,
      unitsSold30d: 6,
      inventory: 80,
      inventoryAgeDays: 60,
      costSource: "estimated",
    },
  },
  {
    id: "winning_campaign",
    label: "Winning Campaign",
    description: "Moderate seller in growth mode",
    expectedStrategyId: "increase_google_budget",
    merchantMode: "growth",
    product: {
      productId: "qa-win-1",
      title: "Hero Vitamin C",
      price: 42,
      unitCost: 10,
      unitsSold30d: 14,
      inventory: 55,
      inventoryAgeDays: 14,
      costSource: "shopify",
    },
  },
  {
    id: "inventory_overstock",
    label: "Inventory Overstock",
    description: "Excess stock with moderate sales",
    expectedStrategyId: "increase_google_budget",
    merchantMode: "cash_flow",
    product: {
      productId: "qa-over-1",
      title: "Overstocked Toner",
      price: 32,
      unitCost: 9,
      unitsSold30d: 12,
      inventory: 200,
      inventoryAgeDays: 75,
      costSource: "shopify",
    },
  },
  {
    id: "seasonal_sales_drop",
    label: "Seasonal Sales Drop",
    description: "Seasonal SKU slowdown",
    expectedStrategyId: "do_nothing",
    merchantMode: "profit",
    product: {
      productId: "qa-season-1",
      title: "Winter Balm",
      price: 28,
      unitCost: 8,
      unitsSold30d: 5,
      inventory: 60,
      inventoryAgeDays: 90,
      costSource: "shopify",
    },
  },
  {
    id: "high_cpc",
    label: "High CPC",
    description: "Margin compressed by ads",
    expectedStrategyId: "increase_google_budget",
    merchantMode: "profit",
    product: {
      productId: "qa-cpc-1",
      title: "Paid Traffic SKU",
      price: 65,
      unitCost: 22,
      unitsSold30d: 4,
      inventory: 50,
      inventoryAgeDays: 45,
      costSource: "estimated",
    },
  },
  {
    id: "low_conversion",
    label: "Low Conversion",
    description: "Traffic but weak conversion",
    expectedStrategyId: "increase_google_budget",
    merchantMode: "growth",
    product: {
      productId: "qa-conv-1",
      title: "Low CR Cleanser",
      price: 24,
      unitCost: 7,
      unitsSold30d: 8,
      inventory: 70,
      inventoryAgeDays: 50,
      costSource: "shopify",
    },
  },
];
