import type { MetaCampaign } from "@/lib/connectors/types";

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();

/** 8 Meta campaigns — 3 winners, 2 average, 3 losing. spend7d totals ~$7,580 */
export const PEAK_OUTFITTERS_META_CAMPAIGNS: MetaCampaign[] = [
  {
    id: "po-meta-summer-hiking",
    name: "Summer Hiking",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    objective: "OUTCOME_SALES",
    dailyBudgetCents: 18_000,
    currency: "USD",
    startTime: daysAgo(45),
    spend7d: 1_200,
    revenue7d: 7_404,
    roas7d: 6.17,
    profit7d: 4_280,
    ctr7d: 2.8,
    frequency7d: 1.6,
    impressions7d: 68_000,
    clicks7d: 1_904,
    conversions7d: 58,
  },
  {
    id: "po-meta-retarget-cart",
    name: "Retargeting — Cart Abandoners",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    objective: "OUTCOME_SALES",
    spend7d: 980,
    revenue7d: 5_880,
    roas7d: 6.0,
    profit7d: 3_420,
    ctr7d: 3.2,
    frequency7d: 2.1,
    impressions7d: 42_000,
    clicks7d: 1_344,
    conversions7d: 44,
  },
  {
    id: "po-meta-brand-trail",
    name: "Brand — Trail Community",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    objective: "OUTCOME_SALES",
    spend7d: 720,
    revenue7d: 3_240,
    roas7d: 4.5,
    profit7d: 1_890,
    ctr7d: 2.4,
    frequency7d: 1.8,
    impressions7d: 38_000,
    clicks7d: 912,
    conversions7d: 28,
  },
  {
    id: "po-meta-spring-collection",
    name: "Spring Collection Launch",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    spend7d: 890,
    revenue7d: 1_200,
    roas7d: 1.35,
    profit7d: -120,
    ctr7d: 1.4,
    frequency7d: 2.4,
    impressions7d: 52_000,
    clicks7d: 728,
    conversions7d: 12,
  },
  {
    id: "po-meta-ig-stories",
    name: "Instagram Stories — Gear Tips",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    spend7d: 650,
    revenue7d: 884,
    roas7d: 1.36,
    profit7d: -80,
    ctr7d: 1.1,
    frequency7d: 2.9,
    impressions7d: 78_000,
    clicks7d: 858,
    conversions7d: 9,
  },
  {
    id: "po-meta-prospecting-broad",
    name: "Prospecting Broad",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    objective: "OUTCOME_SALES",
    spend7d: 2_010,
    revenue7d: 1_166,
    roas7d: 0.58,
    profit7d: -1_680,
    ctr7d: 0.72,
    frequency7d: 3.8,
    impressions7d: 124_000,
    clicks7d: 893,
    conversions7d: 8,
  },
  {
    id: "po-meta-engagement",
    name: "Engagement — Messenger",
    status: "ACTIVE",
    effectiveStatus: "ACTIVE",
    metaEffectiveStatus: "ACTIVE",
    objective: "OUTCOME_ENGAGEMENT",
    spend7d: 280,
    revenue7d: 0,
    roas7d: 0,
    profit7d: -280,
    ctr7d: 0.9,
    frequency7d: 1.2,
    impressions7d: 18_000,
    clicks7d: 162,
    conversions7d: 0,
  },
  {
    id: "po-meta-lal-purchasers",
    name: "LAL 1% Purchasers — Best Audience",
    status: "PAUSED",
    effectiveStatus: "PAUSED",
    metaEffectiveStatus: "ADSET_PAUSED",
    spend7d: 540,
    revenue7d: 2_160,
    roas7d: 4.0,
    profit7d: 1_420,
    ctr7d: 2.6,
    frequency7d: 1.7,
    impressions7d: 24_000,
    clicks7d: 624,
    conversions7d: 22,
  },
  {
    id: "po-meta-video-test",
    name: "Summer Gear — Creative Fatigue",
    status: "PAUSED",
    effectiveStatus: "PAUSED",
    metaEffectiveStatus: "CAMPAIGN_PAUSED",
    spend7d: 850,
    revenue7d: 680,
    roas7d: 0.8,
    profit7d: -520,
    ctr7d: 0.55,
    frequency7d: 4.8,
    impressions7d: 96_000,
    clicks7d: 528,
    conversions7d: 5,
  },
];

export const PEAK_OUTFITTERS_WORST_CAMPAIGN = PEAK_OUTFITTERS_META_CAMPAIGNS.find((c) =>
  c.name.includes("Prospecting Broad"),
)!;
