import type { AttributionDashboard } from "@/lib/attribution/models";
import type { AdvertisingWorkspaceView } from "@/lib/advertising/types";

const EMPTY_BREAK_EVEN = {
  breakEvenRoas: 1.7,
  grossMarginPct: 58,
  contributionMarginPct: 58,
  variableCostRatePct: 42,
  explanation: "Attribution data is not available yet.",
  inputs: [] as { label: string; value: string }[],
};

const EMPTY_STRATEGY_PLAN = {
  strategy: "optimize" as const,
  strategyLabel: "Unavailable",
  targetScope: "none",
  confidencePct: 0,
  reason: "Attribution data is not available yet.",
  preconditions: [],
  strategyAlternatives: [],
  breakEvenModel: EMPTY_BREAK_EVEN,
  businessObjective: "profit" as const,
  businessObjectiveLabel: "Profit",
  confidenceBreakdown: {
    overallPct: 0,
    dataQualityPct: 0,
    sampleSizePct: 0,
    modelFitPct: 0,
    reasons: ["Attribution data is not available yet."],
  },
  expiration: {
    expiresAt: new Date().toISOString(),
    validForHours: 0,
    isExpired: true,
    reason: "Attribution data is not available yet.",
  },
  assumptions: [],
  learningFeedback: [],
  recommendationHistory: [],
  simulation: {
    horizonDays: 30,
    baseline: { spend: 0, revenue: 0, profit: 0, roas: 0 },
    projected: { spend: 0, revenue: 0, profit: 0, roas: 0 },
    delta: { spend: 0, revenue: 0, profit: 0, roas: 0 },
    confidencePct: 0,
    assumptions: [],
  },
  executiveSummary: {
    headline: "Attribution data is not available yet.",
    bullets: [],
    primaryMetricLabel: "—",
    primaryMetricValue: "—",
  },
  objectiveReconciliation: {
    aligned: true,
    objective: "profit" as const,
    note: "Attribution data is not available yet.",
  },
  optimizationWorkflow: [],
  actions: [],
  stability: {
    scorePct: 0,
    label: "Unknown" as const,
    reasons: [],
  },
  metricsSummary: {
    netProfit: 0,
    cacGapPct: null,
    roasGapPct: null,
    totalSpend: 0,
  },
};

/** Empty attribution model used when events/GA4/synth are unavailable. */
export function emptyAttributionDashboard(syncedAt: string): AttributionDashboard {
  return {
    syncedAt,
    model: "position_based",
    confidence: {
      scorePct: 0,
      level: "Low",
      reason: "Attribution data is not available yet.",
      trackingCompletenessPct: 0,
      identityResolutionPct: 0,
      avgTouchpoints: 0,
      missingData: ["attribution_events"],
    },
    channels: [],
    campaigns: [],
    creatives: [],
    acquisition: {
      cac: null,
      newCustomerRoas: null,
      returningCustomerRoas: null,
      paybackPeriodDays: null,
      ltvCacRatio: null,
      newCustomers: 0,
      returningCustomers: 0,
      newCustomerRevenue: 0,
      returningCustomerRevenue: 0,
      bestAcquisitionChannel: null,
    },
    journeySamples: [],
    sampleJourneys: [],
    winningCreatives: [],
    fatiguedCreatives: [],
    assistedLeaders: [],
    bestCampaigns: [],
    worstCampaigns: [],
    strategyPlan: EMPTY_STRATEGY_PLAN as unknown as AttributionDashboard["strategyPlan"],
    attributionOpportunities: [],
  };
}

/** Empty advertising workspace — page stays up when attribution is missing. */
export function emptyAdvertisingWorkspace(syncedAt: string): AdvertisingWorkspaceView {
  return {
    syncedAt,
    overview: {
      healthScore: 0,
      healthTier: "needs_review",
      businessStatus: "Attribution data is not available yet.",
      businessStatusEmoji: "",
      topOpportunity: "Connect ad platforms and ensure order/attribution events sync.",
      expectedMonthlyProfitImprovement: 0,
      spend30d: 0,
      revenue30d: 0,
      blendedRoas: 0,
      aiConfidencePct: 0,
    },
    platforms: [],
    campaigns: [],
    adSets: [],
    ads: [],
    creatives: [],
    audiences: [],
    budgetAllocation: {
      channels: [],
      expectedMonthlyProfit: 0,
      rationale: "Attribution data is not available yet.",
      reasons: [],
    },
    optimizationCenter: [],
    optimizationPackages: [],
    timelines: [],
    aiManager: {
      headline: "Attribution data is not available yet.",
      intro: "StorePilot will build the advertising workspace once attribution data syncs.",
      narrative: "No attributed journeys or spend linkage is available for this store yet.",
      campaignCount: 0,
      platformCount: 0,
      losingMoneyCount: 0,
      scaleReadyCount: 0,
      wasteAudienceCount: 0,
      expectedMonthlyProfitImprovement: 0,
      confidencePct: 0,
      insights: [],
    },
    healthExplanations: [],
    topWinners: [],
    topLosers: [],
    accountability: {
      dailyPriority: {
        title: "Attribution unavailable",
        action: "Wait for attribution sync or connect GA4 / ad platforms",
        estimatedMinutes: 0,
        expectedMonthlyImpact: 0,
        risk: "Low",
        confidencePct: 0,
        narrative: "Attribution data is not available yet.",
      },
      sinceLastVisit: {
        isFirstVisit: true,
        items: [],
      },
      trustEngine: {
        dataQualityPct: 0,
        connectedSources: [],
        historicalCoverageDays: 0,
        confidencePct: 0,
        predictionReliability: "Low",
        summary: "Attribution data is not available yet.",
      },
      accountabilityItems: [],
      learningInsight: null,
      crossModuleAlerts: [],
      predictionTrackRecord: {
        items: [],
        overallAccuracyPct: 0,
        summary: "No predictions measured yet.",
      },
    },
    accountSummary: {
      totalCampaigns: 0,
      healthy: 0,
      needAttention: 0,
      critical: 0,
      improving: 0,
      largestOpportunity: null,
      largestRisk: null,
      headline: "Attribution data is not available yet.",
    },
  };
}
