const MODES = [
  {
    id: "simulation",
    label: "Simulation Mode",
    active: true,
    badge: "You are here",
    description:
      "Artificial business scenarios generated by the StorePilot Simulation Engine.",
    uses: ["AI testing", "Product demos", "Regression testing", "Training"],
  },
  {
    id: "live",
    label: "Live Analysis Mode",
    active: false,
    badge: null,
    description:
      "Uses real Shopify, Meta, Google, GA4, and other connected integrations.",
    uses: ["Daily business recommendations", "Production store monitoring"],
  },
  {
    id: "prediction",
    label: "Prediction Mode",
    active: false,
    badge: "Coming soon",
    description:
      'Ask "What happens if I increase Meta budget by 20%?" or "What if I pause this campaign?" before you act.',
    uses: ["Outcome forecasting", "Decision rehearsal", "Risk preview"],
  },
] as const;

export function SimulationModesBanner() {
  return (
    <section className="card sim-modes-banner" aria-labelledby="sim-modes-heading">
      <div className="sim-modes-header">
        <h3 id="sim-modes-heading">How StorePilot uses data</h3>
        <p className="muted">
          Always know whether you are viewing simulated scenarios, live store data, or future
          predictions.
        </p>
      </div>
      <div className="sim-modes-grid">
        {MODES.map((mode) => (
          <article
            key={mode.id}
            className={`sim-mode-card${mode.active ? " sim-mode-card-active" : ""}`}
          >
            <div className="sim-mode-card-top">
              <h4>{mode.label}</h4>
              {mode.badge ? <span className="sim-mode-badge">{mode.badge}</span> : null}
            </div>
            <p>{mode.description}</p>
            <ul>
              {mode.uses.map((use) => (
                <li key={use}>{use}</li>
              ))}
            </ul>
          </article>
        ))}
      </div>
    </section>
  );
}
