import { notFound } from "next/navigation";
import Link from "next/link";
import { SimulationStoresClient } from "./SimulationStoresClient";
import { isDevValidationEnabled, isDeveloperToolsEnabled } from "@/lib/validation/dev-gate";
import { listSimulationStores } from "@/lib/simulation-stores/db";
import { DEFAULT_SIMULATION_STORES } from "@/lib/simulation-stores/catalog";
import { SimulationBadge } from "@/components/simulation/SimulationBadge";
import { SimulationModesBanner } from "@/components/simulation/SimulationModesBanner";
import { SimulationDataSource } from "@/components/simulation/SimulationDataSource";

export const dynamic = "force-dynamic";

export default async function SimulationStoresPage() {
  if (!isDevValidationEnabled()) {
    notFound();
  }

  const listed = await listSimulationStores();
  const stores = listed.length ? listed : DEFAULT_SIMULATION_STORES;
  const showDeveloperTools = isDeveloperToolsEnabled();

  return (
    <>
      <div className="page-header sim-page-header">
        <div className="sim-page-header-row">
          <div>
            <SimulationBadge variant="page" />
            <h2 style={{ marginTop: 12 }}>Simulation Lab</h2>
            <p>
              Explore <strong>artificial business scenarios</strong> — not real stores. Every
              product, campaign, and metric here is generated by the StorePilot Simulation Engine
              to demonstrate how AI diagnoses problems and recommends actions.
            </p>
          </div>
        </div>
        <SimulationDataSource compact />
        {showDeveloperTools ? (
          <p className="muted" style={{ marginTop: 12, fontSize: "0.85rem" }}>
            <Link href="/dev/decision-quality">Decision Quality Lab</Link>
            {" · "}
            <Link href="/integration-health">Integration Health</Link> (developer tools)
          </p>
        ) : null}
      </div>

      <SimulationModesBanner />

      <SimulationStoresClient
        initialStores={stores}
        showDeveloperTools={showDeveloperTools}
      />
    </>
  );
}
